# Generated by Django 5.0.4 on 2024-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='connected',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
