# Generated by Django 5.0.4 on 2024-04-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0008_alter_userprofilemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connected',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
